#-----------------------------------------------------------------------------------------
#
#GitHub Action Workflow to Deploy Node Red to AWS ElasticBeanstalk                      -
#
#-----------------------------------------------------------------------------------------




name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "node-red-source-development"
  EB_APPLICATION_NAME       : "Node-RED"
  EB_ENVIRONMENT_NAME       : "Production"
  AWS_REGION_NAME           : "eu-central-1"
  DEPLOY_PACKAGE_NAME       : "node-red-on-elastic-beanstalk.zip"


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16,18]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Dependencies
      run: |
       npm install
       npm install -g gulp-cli
       
    - name: Build
      run: |
       gulp minify
       gulp build
    - name: Configure  AWS Credentils
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}

    - name: move file to deployment package
      run : cd dist/ && mv * ${{env.DEPLOY_PACKAGE_NAME}}

    - name: Copy our Deployment package to S3 bucket
      run : cd dist/ && aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/${{env.DEPLOY_PACKAGE_NAME}}

    - name: Create new ElasticBeanstalk Application Version
      run: |
          aws elasticbeanstalk create-application-version \
          --application-name MyAwesomeApp \
          --source-bundle S3Bucket="elasticbeanstalk-eu-west-1-830621850046",S3Key=${{env.DEPLOY_PACKAGE_NAME}}\
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

    - name: Update Environment
      run : |
        aws elasticbeanstalk update-environment \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --version-label v1 \
          --region ${{ env.AWS_REGION_NAME }}
          
