#-----------------------------------------------------------------------------------------
#
#GitHub Action Workflow to Deploy Node Red to AWS ElasticBeanstalk                      -
#
#-----------------------------------------------------------------------------------------
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "node-red-bucket-development"
  EB_APPLICATION_NAME       : "Node-red"
  EB_ENVIRONMENT_NAME       : "developement"
  DEPLOY_PACKAGE_NAME       : "Node-red-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-1"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16,18]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
       npm install
       npm install -g gulp-cli
    - name: Build
      run: |
       gulp minify
       gulp build
    - name: Configure my AWS Credentils
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 

  
    
  

  
