name: Node-red CI/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [16 , 18]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
       npm install
       npm install -g gulp-cli
    - name: Build
      run: |
       gulp minify
       gulp build
       
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         application_name: MyApplicationName
         environment_name: MyApplication-Environment
         version_label: 123453
         region: eu-west-1
         deployment_package: node-red-ha-on-aws/dist/*.zip  
       
 
    
  

  
